#!/bin/bash
gcc $CFILE -o cisfun

#script Explanation
: << 'COMMENT'
Write a script that compiles a C file and creates an executable named cisfun.
The C file name will be saved in the variable $CFILE. Hope this helps alikkle
COMMENT
